#!/usr/bin/env bash

set -e

CONFIG="install.conf.yaml"
DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

echo "Standing up dotbot..."
cd $BASEDIR && git submodule update --init --recursive dotbot/
echo "Standing up dotbot-brew..."
case $OSTYPE in
 darwin* ) cd $BASEDIR && git submodule update --init --recursive dotbot-brew/ ;;
 * ) echo "Nevermind, this isn't a mac";;
esac

echo "Standing up Vundle..."
cd $BASEDIR && git submodule update --init vim/bundle/Vundle.vim

echo "Standing up p10k..."
cd $BASEDIR && git clone --depth=1 https://github.com/romkatv/powerlevel10k.git powerlevel10k

echo "Handing off to dotbot!"

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" --plugin-dir dotbot-brew -c "${CONFIG}" "${@}"
